package net.abesto.jstuki.ui;

import java.util.logging.Level;
import java.util.logging.Logger;
import net.abesto.jstuki.actions.ActionProxy;
import net.abesto.jstuki.actions.ActionProxy.ActionDisabledException;

public class ActionSetLabel extends javax.swing.JPanel {
    private ActionProxy proxy;

    /** Creates new form ActionSetLabel */
    public ActionSetLabel() {
        initComponents();
    }

    public void setProxy(ActionProxy proxy) {
        this.proxy = proxy;
    }

    public void setLabel(String label) {
        txtLabel.setText(label);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLabel = new javax.swing.JTextField();
        btnSetLabel = new javax.swing.JButton();

        btnSetLabel.setText("Set Label");
        btnSetLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSetLabel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSetLabel)
                    .addComponent(txtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetLabelActionPerformed
        try {
            proxy.setLabel(txtLabel.getText());
        } catch (ActionDisabledException ex) {
            Logger.getLogger(ActionSetLabel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSetLabelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSetLabel;
    private javax.swing.JTextField txtLabel;
    // End of variables declaration//GEN-END:variables

}
