package net.abesto.jstuki.ui;

import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.abesto.jstuki.actions.ActionProxy;
import net.abesto.jstuki.elements.Exceptions.HandlerNotSetException;
import net.abesto.jstuki.elements.Statement;

public class ActionsPanel extends javax.swing.JPanel {
    private ActionProxy proxy;

    /** Creates new form ActionsPanel */
    public ActionsPanel() {
        proxy = new ActionProxy();
        initComponents();
    }

    public boolean removeActionListener(ActionListener e) {
        return proxy.removeActionListener(e);
    }

    public boolean addActionListener(ActionListener e) {
        return proxy.addActionListener(e);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionSetLabel = new net.abesto.jstuki.ui.ActionSetLabel();

        actionSetLabel.setProxy(proxy);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(actionSetLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(actionSetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private net.abesto.jstuki.ui.ActionSetLabel actionSetLabel;
    // End of variables declaration//GEN-END:variables

    public void update(Statement selection) {
        if (selection == null) {
            return;
        }
        try {
            proxy.select(selection);
        } catch (HandlerNotSetException ex) {
            Logger.getLogger(ActionsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        actionSetLabel.setLabel(selection.getLabel());
    }
}
