package net.abesto.jstuki.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import net.abesto.jstuki.actions.ElementActionEvent;
import net.abesto.jstuki.actions.ElementActionListener;
import net.abesto.jstuki.elements.*;

public class MainFrame extends javax.swing.JFrame {
    private Procedure p;

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();

        // view selection -> actionsPanel update
        viewTabs.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                CodeListing source = (CodeListing) e.getSource();
                actionsPanel.update(source.getSelectedStatement());
            }
        });

        // actionPanel action -> view update
        actionsPanel.addActionListener(new ElementActionListener() {
            public void actionPerformed(ElementActionEvent e) {
                viewTabs.display(p);
                viewTabs.select(e.getSource());
            }
        });
        displayTest();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitMain = new javax.swing.JSplitPane();
        viewTabs = new net.abesto.jstuki.ui.ViewsTabbedPane();
        actionsPanel = new net.abesto.jstuki.ui.ActionsPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitMain.setDividerLocation(400);

        viewTabs.loadTabs(new File("syntax")) ;
        jSplitMain.setLeftComponent(viewTabs);
        jSplitMain.setRightComponent(actionsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitMain, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitMain, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    public void displayTest() {
        p = new Procedure("PrintEvenFibonacci(limit)");

        p.addChild(new Statement("a = 1"));
        p.addChild(new Statement("b = 1"));

        Iteration i = new Iteration("a < limit");
        Conditional mod = new Conditional();
        mod.addCase("a % 2 == 0");
        mod.addCase("a % 2 == 1");
        mod.addCase("Valami hülyeség");
        mod.getCase("a % 2 == 0").addChild(new Statement("print 'Printed from conditional: ',a"));
        mod.getCase("a % 2 == 1").addChild(new Statement("pass"));
        mod.getCase("Valami hülyeség").addChild(new Statement("jaj hát ilyen elő se fordulhat"));
        mod.getCase("Valami hülyeség").addChild(new Statement("ésakkor ez sincs"));

        i.addChild(mod);

        BinaryConditional binmod = new BinaryConditional("a % 2 == 0");
        binmod.getTrueCase().addChild(new Statement("print 'Printed from binary conditional: ',a"));
        binmod.getFalseCase().addChild(new Statement("pass"));

        i.addChild(binmod);

        i.addChild(new Statement("c = a"));
        i.addChild(new Statement("a = b"));
        i.addChild(new Statement("b = a+b"));

        p.addChild(i);
        viewTabs.display(p);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private net.abesto.jstuki.ui.ActionsPanel actionsPanel;
    private javax.swing.JSplitPane jSplitMain;
    private net.abesto.jstuki.ui.ViewsTabbedPane viewTabs;
    // End of variables declaration//GEN-END:variables

}
